apiVersion: v1
kind: Service
metadata:
  name: example-api 
  labels:
    application: example-api
spec:
  ports:
    - name: http 
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    application: example-api

